config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'restaurants#index'
  
  get '/restaurants/index', 'restaurants#index'
  get '/restaurants/oldest', 'restaurants#oldest'
  get '/restaurants/next', 'restaurants#next'
  get '/restaurants/previous', 'restaurants#previous'
  get '/restaurants/user_history', 'restaurants#user_history'

  
  resources :restaurants, :except => [:destroy] do
    resources :comments
    member do 
      put "will", to: 'restaurants#will'
      put "wont", to: 'restaurants#wont'
      put "favorite", to: 'restaurants#favorite'
    end
  end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  
  belongs_to :user
  acts_as_votable  
  default_scope -> {order(created_at: :desc)}
  validates :name, :street, :city, :state, presence: true
  
  def self.search(search)
    where("name LIKE ? OR state LIKE ? OR street LIKE ? OR city LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  end
  
  has_many :comments
  has_many :favorites
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_voter
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :restaurants
  has_many :comments
  has_many :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_restaurant
  before_action :authenticate_user!
  
  def create
    @comment = @restaurant.comments.build(comment_params)
    @comment.user_id = current_user.id 
    @comment.save
    
    if @comment.save
      redirect_to restaurant_path(@restaurant) 
    else
      render 'new'
    end
  end
  
  private
  
  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
  
  def comment_params 
      params.require(:comment).permit(:content)    
  end
  
end

app/controllers/favorite_controller.rb
class FavoriteController < ApplicationController
  before_action :find_restaurant
  before_action :authenticate_user!
  
  def create
    @favorite = @restaurant.favorites.build(favorite_params)
    @favorite.user_id = current_user.id 
    @favorite.save
    render :index
  end
  
  private
  
  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
  
  def favorite_params 
      params.require(:favorite).permit(:fave, :user_id, :restaurant_id)    
  end
  
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, except: [:index, :new, :create, :next, :previous, :user_history]
  before_action :set_users
  before_action :set_votes, except: [:user_history]
  before_action :set_user_votes, only: [:user_history]
  before_action :set_comments, except: [:user_history]
  before_action :set_user_comments, only: [:user_history]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_favorites, only: [:user_history]

  # GET /restaurants
  # GET /restaurants.json
  def index
    session[:page] = 0
    @restaurants = Restaurant.limit(10).offset(session[:page] * 10) 
    if params[:search]
      @restaurants = Restaurant.search(params[:search])
    else
      @restaurants = Restaurant.all
    end
  end

  def history
     render :history
  end
  
  def favorite
    @favorite = @restaurant.favorites.build(:fave => "true")
    @favorite.user_id = current_user.id 
    @favorite.restaurant_id = params[:id]
    @favorite.save
    redirect_back fallback_location: root_url  
  end
  

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @comments = Comment.where(restaurant_id: @restaurant).order("created_at DESC")
  end

  # GET /restaurants/new
  def new
    @restaurant = current_user.restaurants.build
  end
  
  def will
    @restaurant.vote_by voter: current_user, :vote => 'like', :duplicate => true
    redirect_back fallback_location: root_url  
  end
  
  def wont
    @restaurant.vote_by voter: current_user, :vote => 'bad', :duplicate => true
    redirect_back fallback_location: root_url 
  end
  
  def next
    if (session[:page] == 0) 
      @restaurants = Restaurant.limit(10).offset(session[:page] * 10)      
    else
      session[:page] += 1
      @restaurants = Restaurant.limit(10).offset(session[:page] * 10)   
    end
    render :index     
  end

  def previous
    if (session[:page] == 0) 
      @restaurants = Restaurant.limit(10).offset(session[:page] * 10)      
    else
      session[:page] -= 1
      @restaurants = Restaurant.limit(10).offset(session[:page] * 10)   
    end
    render :index    
  end
  

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = current_user.restaurants.build(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :street, :city, :state)
    end
    
    def set_votes
      @votes = ActsAsVotable::Vote.all      
    end
    
    def set_users
      @users = User.all
    end
    
    def set_comments
      @comments = Comment.all
    end
    
    def set_user_comments
      @comments = Comment.select { |comment| comment.user_id == current_user.id }    
    end
    
    def set_user_votes
      @votes = ActsAsVotable::Vote.select { |vote| vote.voter_id == current_user.id }     
    end
    
    def set_favorites
      @favorites = Favorite.select {|favorite| favorite.user_id == current_user.id }
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/comments/_comment.html.erb
<% i=1 %>
<% @comments.each do |comment| %>
	<p>	
	<strong>Comment: <%= i.to_s %></strong>
	<% if comment.user_id.blank? %>
		<p><%= comment.content %><br> Made By: No User</p>
	<% else %>
		<p><%= comment.content %><br> Made By: <%= @users.find(comment.user_id).email %> On: <%= comment.created_at %></p>
	<% end %>
	<% i+= 1 %>
	</p>
<% end %>

<%= render 'comments/form' %>

app/views/comments/_form.html.erb
<%= form_for([@restaurant, @restaurant.comments.build]) do |f| %>
	<p>
	<%= f.text_area :content %>
	<%= f.submit %>
	</p>
<% end %>

app/views/favorite/_button.html.erb
<%= form_for([@restaurant, @restaurant.favorites.build]) do |f| %>

	<%= f.submit %>
	
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Split</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.controller_name %>'>
  	<div id="banner">
  	  <h1>Do they split the check?</h1>
  	  <h2>A listing of restaurants that split the check</h2>	
  	</div>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <% if user_signed_in? %>
        <%= current_user.email %>
    	<%= link_to "Sign Out", destroy_user_session_path, method: :delete %> 
    	<%= link_to 'User History', restaurants_user_history_path %>
    <% else %>
    	<%= link_to "Sign Up", new_user_registration_path %>
    	<%= link_to "Sign In", new_user_session_path %>
    <% end %>
    <%= yield %>
  </body>
  
  <%= form_tag(restaurants_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Restaurants" %>
    <%= submit_tag "Search", :name => nil %>
  <% end %>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(restaurant) do |f| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <% if restaurant.name.blank? %>
 		<%= f.text_field :name %>   
    <% else %>
		<%= restaurant.name %>    	
    <% end %>

  </div>

  <div class="field">
    <%= f.label :street %>
    <% if restaurant.street.blank? %>
    	<%= f.text_field :street %>     
    <% else %>
		<%= restaurant.street %>    
    <% end %>

  </div>

  <div class="field">
    <%= f.label :city %>
    <% if restaurant.city.blank? %>
    	<%= f.text_field :city %>      
    <% else %>
 		<%= restaurant.city %>  
    <% end %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <% if restaurant.state.blank? %>
    	<%= f.text_field :state %>     
    <% else %>
 		<%= restaurant.state %>   
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Vote on the Restaurant!</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Will split</th>
      <th>Wont split</th>
      <th>Details</th>
      <% if user_signed_in? %>
      	<th>+</th>
      	<th>-</th>
      <% end %>
      <th>Last Voted On</th>
      <th>By: </th>
    </tr>
  </thead>
  
  <% if @restaurants.blank? %>
   <h4> There are no restaurants with that name or location name</h4>
  <% end %>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.street %></td>
        <td><%= restaurant.city %></td>
        <td><%= restaurant.state %></td>
        <td><%= restaurant.get_upvotes.size %></td>
        <td><%= restaurant.get_downvotes.size %></td>
        <td><%= link_to 'Comments', restaurant %></td>
        <% if user_signed_in? %>
        	<td><%= link_to  'Will split', will_restaurant_path(restaurant), method: :put %></td>
        	<td><%= link_to 'Wont Split', wont_restaurant_path(restaurant), method: :put %></td>
        <% end %>
        <% if restaurant.get_upvotes.size > 0 || restaurant.get_downvotes.size > 0 %>
        	<td><%= @votes.where(votable_id: restaurant.id).last.created_at.to_s %></td>	
			<td><%= @users.where(id: @votes.where(votable_id: restaurant.id).last.voter_id).last.email  %></td>
		<% else %>
			<td>No votes yet</td>
			<td>No votes yet</td>
		<% end %>
        <% if user_signed_in? %>
        	<% if Favorite.find {|favorite| favorite.restaurant_id == restaurant.id && favorite.user_id == current_user.id }.blank? %>
        		<td><%= link_to  'Favorite?', favorite_restaurant_path(restaurant), method: :put %></td>
        	<% else %>
        		<td>Already a favorite!</td>
        	<% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
<%= link_to 'Newest', restaurants_path %></button>
<%= link_to 'Previous 10 Restaurants', restaurants_previous_path %>
<%= link_to 'Next 10 Restaurants', restaurants_next_path %>
</div>

<br>
<div>
<% if user_signed_in? %>
	<%= link_to 'Add New Restaurant', new_restaurant_path %>
<% end %>	

</div>
<br>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @restaurant.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @restaurant.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @restaurant.state %>
</p>	

<p>
	
<p>
  <%= render 'comments/comment' %>
</p>


<%= link_to 'Back', restaurants_path %>

app/views/restaurants/user_history.html.erb
<p id="notice"><%= notice %></p>

<h1>User History For: <%= current_user.email %></h2>

<h2>User Comment History</h2>
  <% if @comments.blank? %>
    <h4><%= current_user.email %> has not yet made any comments.</h4>
  <% else %>
	<table>
  		<thead>
    		<tr>
      			<th>Comment</th>
      			<th>About</th>
      			<th>On</th>
    		</tr>
  		</thead>
  		<tbody>
    		<% @comments.each do |comment| %>
      			<tr>
        			<td><%= comment.content %></td>
        			<td><%= Restaurant.where(id: comment.restaurant_id).last.name.to_s %></td>
        			<td><%= comment.created_at %></td>
      			</tr>
    		<% end %>
  		</tbody>
	</table>
  <% end %>

<h2>User Voting History</h2>
  <% if @votes.blank? %>
    <h4><%= current_user.email %> has not voted yet.</h4>
  <% else %>
	<table>
  		<thead>
    		<tr>
      			<th>Voted On</th>
      			<th>Voted</th>
      			<th>On</th>
    		</tr>
  		</thead>
  		<tbody>
    		<% @votes.each do |vote| %>
      			<tr>
        			<td><%= vote.votable_id %></td>
        			<% if vote.vote_flag == true %>
        				<td>Will Split</td>
        			<% else %>
        				<td> Wont Split</td>
        			<% end %>
        			<td><%= vote.created_at %></td>
      			</tr>
    		<% end %>
  		</tbody>
	</table>
  <% end %>
<h2>User Favorites</h2>
  <% if @favorites.blank? %>
    <h4><%= current_user.email %> has no favorites.</h4>
  <% else %>
	<table>
  		<thead>
    		<tr>
      			<th>Restaurant Name</th>
      			<th>Favorited On</th>
    		</tr>
  		</thead>
  		<tbody>
    		<% @favorites.each do |favorite| %>
      			<tr>
        			<td><%= Restaurant.where(id: favorite.restaurant_id).last.name.to_s %></td>
        			<td><%= favorite.created_at %></td>
      			</tr>
    		<% end %>
  		</tbody>
	</table>  
  <% end %>
<br>
<%= link_to 'Back', restaurants_path %>